### ISSUE TITLE
Communicate via user's their GITHUB e-mail address

### ISSUE THREAD

**Issue by nmcb** [zalando/play-swagger#109]
We should (as this is an OSS project) allow the most convenient e-mail address for all communication between collaborators, preferable the same as which is publicly available on github:

- Slava Schmidt: slavaschmidt@gmx.de
- Marco Borst: marco@splatter.nl

Implement: Notify the stakeholder hierarchy top down.

**Comment by nmcb** [comment]
@slavaschmidt Labeled bug as we probably missed out on communication via our Zalando e-mail accounts.

**Comment by LappleApple** [comment]
@nmcb @slavaschmidt Does "Implement: Notify the stakeholder hierarchy top down." mean talking to Zalando stakeholders or other? Let me know if you need a useful email address on this to add.
