### ISSUE TITLE
Simplify dependency setup

### ISSUE THREAD

**Issue by benmccann** [zalando/play-swagger#29]
The README says:

>change the scope of the spec2 dependency by removing % Test
"org.scalacheck" %% "scalacheck" % "1.12.4", "org.specs2" %% "specs2-scalacheck" % "3.6"  to the list of the libraryDependencies

The plugin should be able to add these dependencies so that the user doesn't have to.

However, why is it that that they're currently needed? spec2 is a test library and should only be needed in the `Test` scope. If it's being added because it's needed to generate code then it should be on the sbt classpath and not on the application classpath.

**Comment by slavaschmidt** [comment]
Sure, these dependencies belong to the test/sbt class path. They are in app class path for now because the prototype has only application scope for code generation. This will be addressed as soon as we start generating test data in production-quality version of the plugin.

**Comment by slavaschmidt** [comment]
Fixed in 0.1.5
