### ISSUE TITLE
Remove scalaz bintray resolver

### ISSUE THREAD

**Issue by benmccann** [zalando/play-swagger#30]
Why do we need this line?

    resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

I though scalaz was on Maven Central now. See https://github.com/scalaz/scalaz-stream/issues/258

If we need to keep it for some reason, then we should at least switch it to https for security. See http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/

**Comment by slavaschmidt** [comment]
Fixed
