### ISSUE TITLE
Fix continuous build test suite

### ISSUE THREAD

**Issue by benmccann** [zalando/play-swagger#32]
It'd be really nice to get the continuous build passing so that if I send you some more complex changes I can feel a bit safer that I'm not breaking anything. Would it be better to fix or disable the failing tests? I'm not sure what the current state is

**Comment by slavaschmidt** [comment]
The main development branch is "newnaming" for now. The build is OK for this branch. We hope to merge it into the master really soon, just waiting the new AST part to be finished.

**Comment by slavaschmidt** [comment]
Disabled two failing tests because of the issues with current jackson-json-reference implementation. Will re-enable as soon as new version of jackson-json-reference is available
