### ISSUE TITLE
parameter type formData is not supported yet

### ISSUE THREAD

**Issue by slavaschmidt** [zalando/play-swagger#35]
We need to handle this parameter type special in two places: 
1. The controller base. Here the parameter should be unmarshalled from the request body as described in https://www.playframework.com/documentation/2.0/ScalaForms
2. Tests. Here parameters of this type should be marshalled and attached to the request as a body

**Comment by remy-phelipot** [comment]
Hello,

I really need this feature for my project, so I may help you for the implementation. Is it possible to give me some clue? What are the interesting trait or class to modify?

Rémy

**Comment by slavaschmidt** [comment]
@remy-phelipot Cool, thanks for reaching out!
We plan to make plugin feature complete as a next step. This will include support for files as well. I'll start to work on this feature next week.

Probably a couple of places will change, including the controller template. I'm not really sure for now, as I don't have a clear idea how to implement this feature in most non-invasive way.

**Comment by remy-phelipot** [comment]
Ok, glad to hear that! Feel free to ask if you need help.

**Comment by slavaschmidt** [comment]
resolved in master
