### ISSUE TITLE
Illegal package names generated when YAML filename contains dashes

### ISSUE THREAD

**Issue by alexkops** [zalando/play-swagger#47]
When you use dashes in your YAML file name, like "my-api.yaml", then it won't compile, since the package name will be
```
package my-api.yaml
```
and it cannot contain dashes.

**Comment by slavaschmidt** [comment]
Fixed in https://github.com/zalando/play-swagger/commit/e587458f21b93797b4c98a2564fd280e44491cf8

**Comment by slavaschmidt** [comment]
Fixed in 0.1.5
