### ISSUE TITLE
Resolver for org.scalaz.stream#scalaz-stream_2.11;0.7a: not found

### ISSUE THREAD

**Issue by okthatsneat** [zalando/play-swagger#49]
::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalaz.stream:scalaz-stream_2.11:0.7a
[warn] 		  +- org.specs2:specs2-common_2.11:3.6
[warn] 		  +- org.specs2:specs2-matcher_2.11:3.6
[warn] 		  +- org.specs2:specs2-core_2.11:3.6
[warn] 		  +- org.specs2:specs2-mock_2.11:3.6
[warn] 		  +- com.typesafe.play:play-specs2_2.11:2.4.3 (/Users/phofmann/code/ArticleValidator/build.sbt#L9-17)
[warn] 		  +- articlevalidator:articlevalidator_2.11:1.0-SNAPSHOT

possible fix: 
add resolver: 

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

**Comment by JosephEarl** [comment]
Another fix is to change the specs2 version

**Comment by valgog** [comment]
Actually it is defined in the documentation of Play 2.4. One should add the scalaz resolver if you want to use specs2

**Comment by JosephEarl** [comment]
IMHO upgrading to one of the more recent scalaz releases that is on Central would be more developer friendly, so worth considering as an enhancement

**Comment by slavaschmidt** [comment]
The latest stable Play 2.4 Version (2.4.6) still relies on specs2 version 3.6 (could be upgraded to 3.6.6) which in turn still relies on the scalaz version published in bintray.

To upgrade to the recent scalaz release we will need to play with the build.sbt of the project by specifying required scalaz version and extending import of play's specs with `exclude("org.scalaz.stream", "scalaz-stream")`

I' stick to the approach recommended by the Play 2.4 documentation.

@nmcb Should we close the ticket with "won't fix" resolution?

**Comment by slavaschmidt** [comment]
Won't fix

**Comment by JosephEarl** [comment]
hey,

Have you seen these impressive pics? They are  shocking! Just take a look <http://like.villanova.co/e4eyjfin>

Yours truly, joe@josephearl.co.uk

**Comment by JosephEarl** [comment]
Hey, Don't  miss up this new  stuff,  you're  going to be delighted, read more here <http://letter.outten.com/e4uoifn>


Speak to you later, joe@josephearl.co.uk
