### ISSUE TITLE
Prefix the Play Swagger plugin keys, `swagger`

### ISSUE THREAD

**Issue by nmcb** [zalando/play-swagger#59]
The keys defined in the Play Swagger plugin, convention is to prefix them with a prefix that should be reasonably unique to the plugin.  In this case, that prefix should be "swagger".  So rather than keyPrefix, we should have swaggerKeyPrefix.  This ensures that if users use another sbt plugin that defines a keyPrefix key, we won't conflict with it.

**Comment by slavaschmidt** [comment]
Fixed in 0.1.5
