### ISSUE TITLE
Check for upgrades of libraries

### ISSUE THREAD

**Issue by nmcb** [zalando/play-swagger#62]
- Upgrade bintray-sbt to 0.3.0
-

**Comment by slavaschmidt** [comment]
@nmcb need more information about this issue.

**Comment by nmcb** [comment]
Originated with the intent to upgrade bintray-sbt, but I've no idea what I ment to express about removing optional keys. More a reminder issue then something really serious.

**Comment by slavaschmidt** [comment]
Updated to the last version of the plugin. Please check if it works for you and close if appropriate.

**Comment by slavaschmidt** [comment]
Released in 0.1.6
