### ISSUE TITLE
Sometimes swagger artefacts are not generated

### ISSUE THREAD

**Issue by slavaschmidt** [zalando/play-swagger#85]
Sometimes no swagger artefacts generated until clean command is issued.

**Comment by slavaschmidt** [comment]
Apparently, this kind of definition is ignored as well: ```swaggerDefinitions := Seq(file("api.json"))```

**Comment by nmcb** [comment]
@slavaschmidt Is the issue reproducible?

**Comment by slavaschmidt** [comment]
I'm able to reproduce it by starting ```sbt```, issuing ```swagger``` to generate source files and than leaving ```sbt```
sometimes there are couple of files generated and at the next iteration nothing at all

**Comment by nmcb** [comment]
@slavaschmidt I'll have a look at it.

**Comment by slavaschmidt** [comment]
Got it

**Comment by slavaschmidt** [comment]
Related to #100

**Comment by slavaschmidt** [comment]
Should be fixed now

**Comment by slavaschmidt** [comment]
Fixed in 0.1.7
